force-app/main/default/objects/Inspection_Form__c/Inspection_Form__c.object-meta.xml
<CustomObject>
    <label>Inspection Form</label>
    <nameField>
        <displayFormat>I-{00000}</displayFormat>
        <label>Inspection Form Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inspection Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Inspection_Form__c/fields/Make__c.field-meta.xml
<CustomField>
    <fullName>Make__c</fullName>
    <label>Make</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Honeywell</fullName>
            </value>
            <value>
                <fullName>Delta</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Inspection_Form__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Process</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/InspectionTrackingProcessBuilderTest.cls
@isTest
public class InspectionTrackingProcessBuilderTest {
    
    @testSetup
    private static void InsertTestOpp() {

	   // Construct a test Inspection
        Inspection_Form__c  ins = new Inspection_Form__c (Make__c  = 'test model',
                                          Status__c = 'In Progres');

	   // Save this Inspection to the database
        insert ins;
    }
    
    @isTest
private static void UpdateInspectio_ChangeTracked_ProcessFired() {
        
    // Load the ispection:
    Inspection_Form__c loadedIns = [SELECT id
                             FROM Inspection_Form__c];
        
    // Set the model value to something else:
    loadedIns.Make__c = 'Model-5';
        
    // Save it to the database, and fire the process builder
    test.startTest();
        update loadedIns;
    test.stopTest();
        
    // Load the tracking record for this Opportunity
    List<Inspection_Form__c> resultIns = [SELECT id, name
                             FROM Inspection_Form__c where Make__c='Model-5'];
    
    System.assertEquals(1, resultIns.size());

}


}